# Generated by Django 4.2.11 on 2024-06-14 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firestation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='firestation',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='firestation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='firestation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
